const keypointsMapping = {
    "Signer human name": "signer_human_name",
    "Signer company name": "signer_company_name",
    "Signer details": "signer_details",
    "Signee human name": "signee_human_name",
    "Signee company name": "signee_company_name",
    "Signee details": "signee_details",
    "Contract type": "contract_type",
    "Contract details": "contract_details",
    "Effective Date": "effective_date",
    "Contract Duration": "contract_duration",
    "Renewal Term": "renewal_term",
    "Expiration Date": "expiration_date",
    "Jurisdiction": "jurisdiction",
    "Notice Period": "notice_period",
    "Terms for Renewal": "terms_for_renewal",
    "Termination and Expiry": "termination_and_expiry",
    "Deliverables and Obligations": "deliverables_and_obligations",
    "Payment Frequency": "payment_frequency",
    "Contract Value": "contract_value",
    "Liability Cap": "liability_cap",
    "Business Liability": "business_liability",
    "Indemnifying Party": "indemnifying_party"
    }